spring:
  application:
    name: user-service
  profiles:
    active: dev
    include: kafka,redis
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}/"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL}