name: user-service CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: secret
        options: >-
          --health-cmd="mongosh --username root --password secret --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      zookeeper:
        image: zookeeper:3.8
        ports:
          - 2181:2181
        options: >-
          --health-cmd="echo ruok | nc localhost 2181 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --health-start-period=40s

      kafka:
        image: confluentinc/cp-kafka:7.4.3
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "bash -c 'kafka-topics --bootstrap-server localhost:9092 --list || exit 1'"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=10
          --health-start-period=60s

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Wait for MongoDB to be ready
        run: |
          echo "⏳ Waiting for MongoDB..."
          for i in {1..30}; do
            nc -z localhost 27017 && echo "✅ MongoDB is up!" && break
            echo "Waiting for MongoDB... attempt $i"
            sleep 2
          done

      - name: Wait for Redis to be ready
        run: |
          echo "⏳ Waiting for Redis..."
          for i in {1..20}; do
            nc -z localhost 6379 && echo "✅ Redis is up!" && break
            echo "Waiting for Redis... attempt $i"
            sleep 2
          done

      - name: Wait for Zookeeper to be ready
        run: |
          echo "⏳ Waiting for Zookeeper..."
          for i in {1..20}; do
            nc -z localhost 2181 && echo "✅ Zookeeper is up!" && break
            echo "Waiting for Zookeeper... attempt $i"
            sleep 2
          done

      - name: Wait for Kafka to be ready
        run: |
          echo "⏳ Waiting for Kafka..."
          for i in {1..30}; do
            nc -z localhost 9092 && echo "✅ Kafka is up!" && break
            echo "Waiting for Kafka... attempt $i"
            sleep 2
          done

      - name: Run tests
        env:
          MONGO_DB_URI: ${{ db_envs.MONGO_DB_URI }}
        run: mvn -B clean verify -DskipITs=false
