name: user-service CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: secret
        options: >-
          --health-cmd="mongosh --username root --password secret --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      zookeeper:
        image: zookeeper:3.8
        ports:
          - 2181:2181
        options: >-
          --health-cmd="echo ruok | nc localhost 2181 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --health-start-period=40s

      kafka:
        image: confluentinc/cp-kafka:7.4.3
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "bash -c 'kafka-topics --bootstrap-server localhost:9092 --list || exit 1'"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "✅ MongoDB is up!" && exit 0
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "❌ MongoDB did not start in time" && exit 1

      - name: Run tests
        env:
          MONGO_DB_URI: mongodb://root:secret@localhost:27017/mydatabase?authSource=admin&authMechanism=SCRAM-SHA-256
        run: mvn -B clean verify -DskipITs=false
